### ISSUE TITLE
tui crashes sometimes :/

### ISSUE THREAD

**Issue by amtoine** [amtoine/nu_plugin_explore#55]
## the error
```
thread '<unnamed>' panicked at src/tui/event.rs:53:26:
failed to send terminal event: SendError { .. }
```

## reproduce
i'm not sure how to reproduce this...
just press keys and that should happen at some point :grimacing:

**Comment by WindSoilder** [comment]
I can reproduce it, And I get another error
```
thread '<unnamed>' panicked at src/tui/event.rs:46:45:
no events available: Os { code: 5, kind: Uncategorized, message: "Input/output error" }
```

here is screenshot

[![asciicast](https://asciinema.org/a/rKqmLgLWdZpwwlsanaGFO2rvp.svg)](https://asciinema.org/a/rKqmLgLWdZpwwlsanaGFO2rvp)

**Comment by fdncred** [comment]
I've been able to make it crash on demand with `ls | nu_plugin_explore` `j` `j` `l` `q` and also with `ls | nu_plugin_explore` `q`.

Screenshot from repetitive jjlq
![image](https://github.com/amtoine/nu_plugin_explore/assets/343840/abcebffe-b323-4e6b-a358-b975eb5bc22b)


```
❯ ls | nu_plugin_explore
thread '<unnamed>' panicked at src/tui/event.rs:46:45:
no events available: Os { code: 5, kind: Uncategorized, message: "Input/output error" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by the-busy-beaver** [comment]
i'm not able to reproduce this error with the following install of Nushell and `nu_plugin_explore` built from the `main` branch :confused: 
weird...

| k                  | v                                               |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.0                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 0                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77-x86_64-unknown-linux-gnu                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-02 09:22:23 +02:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | clipboard, explore                              |

**Comment by fdncred** [comment]
I'm on 0.93.1 in Windows now and so I've changed the cargo.toml to use my dev branch of nushell.
```toml
nuon = { package = "nuon", path = "../nushell/crates/nuon", version = "0.93.1" }
nu-plugin = { package = "nu-plugin", path = "../nushell/crates/nu-plugin", version = "0.93.1" }
nu-protocol = { package = "nu-protocol", features = ["plugin"], path = "../nushell/crates/nu-protocol", version = "0.93.1" }
```
 No issues on Windows. I can't repro the issue here.

|key|value|
|-|-|
|version|0.93.1|
|major|0|
|minor|93|
|patch|1|
|branch|main|
|commit_hash|0805f1fd90974f7ad2f3a54228368f88dcba261f|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.77.2 (25ef9e3d8 2024-04-09)|
|rust_channel|1.77.2-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.77.2 (e52e36006 2024-03-26)|
|build_time|2024-05-02 09:04:09 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, sqlite, system-clipboard, trash, which|
|installed_plugins|bg, emoji, explore, file, formats, from_parquet, gstat, inc, json_path, jwalk, md, msgpack, pnet, polars, query, query_git, regex, str_similarity|

**Comment by the-busy-beaver** [comment]
@fdncred does this dev branch include a patch that could have solved the issue?
or maybe it never crashed on Windows, only on your macos?

**Comment by fdncred** [comment]
> @fdncred does this dev branch include a patch that could have solved the issue? or maybe it never crashed on Windows, only on your macos?

It includes whatever is in your latest main branch. I made sure to pull the latest changes. I may be isolated to MacOS.
