### ISSUE TITLE
Strange error happened when typing q after explore

### ISSUE THREAD

**Issue by WindSoilder** [amtoine/nu_plugin_explore#60]
I've compiled on latest main branch, but I get the following error when type q after explore:
## First run
```
thread '<unnamed>' panicked at src/tui/event.rs:57:50:
failed to send tick event: SendError { .. }
```
## Second run
```
thread '<unnamed>' panicked at src/tui/event.rs:46:45:
no events available: Os { code: 5, kind: Uncategorized, message: "Input/output error" }
```
## Screenshot
[![asciicast](https://asciinema.org/a/rKqmLgLWdZpwwlsanaGFO2rvp.svg)](https://asciinema.org/a/rKqmLgLWdZpwwlsanaGFO2rvp)

**Comment by WindSoilder** [comment]
Closing it in favor of #55
